# Generated by Django 6.0.5 on 2026-06-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudo', '0002_loginm_registerm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registerM',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='loginM',
        ),
    ]
